- name: Configuring mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy the mongo repo
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    package:
      name: mongodb-org
      state: present
  
  - name: Start the service
    service:
      name: "mongodb"
      state: started